language: python

sudo: false

python:
  - "3.6"

install:
  - pip install -r requirements.txt

cache:
  - pip

os:
  - os

branches:
  only:
    - master

env:
  - PYTHON_VERSION="3.6"

script:
 - python --version
