language: python

sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

cache:
  - pip

os:
  - linux
  - osx

branches:
  only:
    - master
    
env:
  - PYTHON_VERSION="2.7"
  - PYTHON_VERSION="3.5"
  - PYTHON_VERSION="3.6"
